### ISSUE TITLE
Support Python-style programming construct

### ISSUE THREAD

**Issue by tengpeng** [eclecticlogic/stepper#1]
I am working on an open source project that translates python-style programming construct to AWS step function. Luckily I find Stepper has already done great job in translating Java-style. 

I have dived into the code base and I am impressed by the solution Stepper provided.

I know you may not have bandwidth now but I am wondering if you can consider provide python-style programming construct. This is valuable for data scientists/data engineers/data analysts, because python is their mother tongue. Thanks.

**Comment by k-abram** [comment]
Would you be able to share what a python-style programming construct would look like (perhaps taking the Fibonacci generator as an example)? Stepper really has a quasi javascript/json style to it.

**Comment by tengpeng** [comment]
Definitely. Take Fibonacci generator as an example:

```
TimeoutSeconds = 120 #Although Python supports annotations, it is more common to assign value.

sqs = task_id # This is NOT for Python-style, but I am thinking if it is possible to define a few tasks as global variables "task_id" so that users like data scientists can refer this tasks rather than defining this tasks multiple times. What do you think?

#Generate Fibonnaci numbers
def Fibonnaci():
    previous = 1            #Required to indent 4 spaces instead of ";"
    fib = 0
  
   for c in range(10):      #Reference: https://docs.python.org/3/tutorial/controlflow.html
       body = fib + ""      #Indent another 4 spaces instead of ";"
       sqs
    
   temp = fib #The same except ";"
   fib += previous
   previous = temp
```

Does it make sense to you? 

(Yes, I should have said quasi javascript/json style)

**Comment by k-abram** [comment]
I think the challenge will be to disambiguate annotation declarations (Timeout = 120) from variable assignments. Also, the calls to activities and external services (like SQS) require additional parameters that are service dependent. You have to express these so that semantically they are clear in their purpose. 
I don't have the bandwidth to make a python version - but two options I would suggest - use Antlr w/ python to create a python version of Stepper following a pattern similar to Stepper or you build a python to Stepper converter and then a tool to take you from Python to Stepper to step-function seamlessly. I don't know that the latter is advantageous if Python to Stepper is not a significantly easier effort.
